plugins:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Layout/LineLength:
  Max: 100
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
  AllowedPatterns:
    - 'https?://\S+'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Metrics/MethodLength:
  Max: 15
Metrics/AbcSize:
  Max: 25